/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eef6eb",
        "on-background": "#161d17",
        "primary-container": "#4ade80",
        "surface-tint": "#006d36",
        "badge-purple-text": "#581C87",
        "text-secondary": "#475569",
        "inverse-surface": "#2b322b",
        "primary": "#006d36",
        "on-tertiary-fixed-variant": "#6c3a0f",
        "outline-variant": "#bccabb",
        "badge-green-text": "#14532D",
        "surface-container-highest": "#dde5da",
        "surface-container-high": "#e2ebe0",
        "primary-fixed-dim": "#4de082",
        "badge-purple-bg": "#E9D5FF",
        "accent-pink": "#F472B6",
        "primary-fixed": "#6dfe9c",
        "on-primary": "#ffffff",
        "accent-yellow": "#FACC15",
        "on-error-container": "#93000a",
        "badge-green-bg": "#BBF7D0",
        "secondary-fixed": "#f0dbff",
        "on-surface": "#161d17",
        "on-tertiary-container": "#794418",
        "badge-yellow-bg": "#FEF08A",
        "inverse-on-surface": "#ebf3e8",
        "on-secondary-container": "#510c8a",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdcc6",
        "surface-dim": "#d4dcd2",
        "secondary": "#7b41b4",
        "surface-container": "#e8f0e5",
        "on-secondary-fixed-variant": "#62259b",
        "error-container": "#ffdad6",
        "surface-variant": "#dde5da",
        "surface-bright": "#f3fcf0",
        "error": "#ba1a1a",
        "tertiary-container": "#ffb47f",
        "tertiary": "#895024",
        "on-primary-container": "#005e2d",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#301400",
        "tertiary-fixed-dim": "#ffb784",
        "background": "#F8FAFC",
        "secondary-container": "#c185fd",
        "badge-pink-bg": "#F472B6",
        "on-surface-variant": "#3d4a3e",
        "inverse-primary": "#4de082",
        "badge-pink-text": "#831843",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#2c0051",
        "on-primary-fixed-variant": "#005227",
        "surface": "#FFFFFF",
        "surface-container-lowest": "#ffffff",
        "text-primary": "#0F172A",
        "secondary-fixed-dim": "#ddb8ff",
        "badge-yellow-text": "#713F12",
        "on-primary-fixed": "#00210c",
        "outline": "#6d7b6d",
        "border-black": "#0F172A",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        xl: "20px",
        sm: "8px",
        lg: "16px",
        md: "12px",
        "2xl": "24px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["1.5rem", { lineHeight: "1.2", fontWeight: "800" }],
        "headline-md": ["1.125rem", { lineHeight: "1.3", fontWeight: "700" }],
        "body-sm": ["0.75rem", { lineHeight: "1.4", fontWeight: "400" }],
        "label-bold": ["0.75rem", { lineHeight: "1.0", fontWeight: "700" }],
        "label-caps": ["0.7rem", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-md": ["0.875rem", { lineHeight: "1.5", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
